# Generated by Django 5.2.6 on 2025-09-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_club_announcement_event_membership_pendingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
